[project]
name = "saras-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-bigquery>=1.9.1",
    "dbt-core>=1.9.4",
    "google-cloud-bigquery>=3.31.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
